spring:
  application:
    name: bank-api

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/bank_api}
    username: ${DB_USERNAME:bank_user}
    password: ${DB_PASSWORD:bank_password}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

admin:
  bootstrap:
    email: ${ADMIN_EMAIL:}
    password: ${ADMIN_PASSWORD:}
    first-name: ${ADMIN_FIRST_NAME:System}
    last-name: ${ADMIN_LAST_NAME:Administrator}
    birth-date: ${ADMIN_BIRTH_DATE:1970-01-01}
    phone: ${ADMIN_PHONE:}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:3600000}

server:
  port: 8080