CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,

    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    middle_name VARCHAR(100),

    birth_date DATE NOT NULL,
    phone VARCHAR(20) NOT NULL UNIQUE,

    role VARCHAR(20) NOT NULL DEFAULT 'CLIENT',
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_users_role
        CHECK (role IN ('CLIENT', 'ADMIN')),

    CONSTRAINT chk_users_status
        CHECK (status IN ('ACTIVE', 'BLOCKED'))
);


CREATE TABLE bank_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    account_number VARCHAR(20) NOT NULL UNIQUE,

    user_id BIGINT NOT NULL,

    balance DECIMAL(19, 2) NOT NULL DEFAULT 0,
    currency VARCHAR(3) NOT NULL DEFAULT 'RUB',


    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_bank_accounts_user
        FOREIGN KEY (user_id)
            REFERENCES users(id),

    CONSTRAINT chk_bank_accounts_balance
        CHECK (balance >= 0),

    CONSTRAINT chk_bank_accounts_currency
        CHECK (currency IN ('RUB')),

    CONSTRAINT chk_bank_accounts_status
        CHECK (status IN ('ACTIVE', 'BLOCKED', 'CLOSED'))
);


CREATE TABLE cards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    card_number VARCHAR(16) NOT NULL UNIQUE,

    bank_account_id BIGINT NOT NULL UNIQUE,

    expiration_date DATE NOT NULL,

    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_cards_bank_account
        FOREIGN KEY (bank_account_id)
            REFERENCES bank_accounts(id),

    CONSTRAINT chk_cards_status
        CHECK (status IN ('ACTIVE', 'BLOCKED', 'EXPIRED', 'CLOSED'))
);


CREATE TABLE transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    type VARCHAR(20) NOT NULL,

    source_account_id BIGINT,
    destination_account_id BIGINT,

    amount DECIMAL(19, 2) NOT NULL,

    description VARCHAR(500),

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_transactions_source_account
        FOREIGN KEY (source_account_id)
            REFERENCES bank_accounts(id),

    CONSTRAINT fk_transactions_destination_account
        FOREIGN KEY (destination_account_id)
            REFERENCES bank_accounts(id),

    CONSTRAINT chk_transactions_type
        CHECK (type IN ('DEPOSIT', 'WITHDRAWAL', 'TRANSFER')),

    CONSTRAINT chk_transactions_amount
        CHECK (amount > 0),

    CONSTRAINT chk_transactions_accounts
        CHECK (
            (type = 'DEPOSIT'
                 AND source_account_id IS NULL
                 AND destination_account_id IS NOT NULL)
                OR
            (type = 'WITHDRAWAL'
                 AND source_account_id IS NOT NULL
                 AND destination_account_id IS NULL)
                OR
            (type = 'TRANSFER'
                 AND source_account_id IS NOT NULL
                 AND destination_account_id IS NOT NULL)
            )
);


CREATE INDEX idx_bank_accounts_user_id
    ON bank_accounts(user_id);

CREATE INDEX idx_transactions_source_account_id
    ON transactions(source_account_id);

CREATE INDEX idx_transactions_destination_account_id
    ON transactions(destination_account_id);

CREATE INDEX idx_transactions_created_at
    ON transactions(created_at);